[build]
  publish = "."
  command = "# no build command"

# Global redirects to remove trailing slashes
[[redirects]]
  from = "/*/"
  to = ":splat"
  status = 301
  force = true

# Ensure specific pages are properly redirected
[[redirects]]
  from = "/blog/"
  to = "/blog"
  status = 301
  force = true

[[redirects]]
  from = "/books/"
  to = "/books"
  status = 301
  force = true 